# Generated by Django 5.1.3 on 2024-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(choices=[('NEW', 'Свежее'), ('POP', 'Популярное'), ('INC', 'Происшествия'), ('SPO', 'Спорт'), ('SHB', 'Шоу-бизнес'), ('INT', 'Интернет'), ('CAR', 'Автомобили'), ('CUL', 'Культура'), ('POL', 'Политика'), ('SOC', 'Общество'), ('TEC', 'Наука и технологии'), ('ECN', 'Экономика'), ('REL', 'Религия'), ('WIL', 'Живая природа'), ('ECO', 'Экология')], default='NEW', max_length=3, unique=True)),
            ],
        ),
    ]
