# Generated by Django 5.1.5 on 2025-04-14 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Перечень категорий'},
        ),
        migrations.AlterModelOptions(
            name='subscriberscategory',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Имя Фамилия пользователя'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating_user',
            field=models.IntegerField(default=0, verbose_name='Рейтинг автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(choices=[('NEW', 'Свежее'), ('POP', 'Популярное'), ('INC', 'Происшествия'), ('SPO', 'Спорт'), ('SHB', 'Шоу-бизнес'), ('INT', 'Интернет'), ('CAR', 'Автомобили'), ('CUL', 'Культура'), ('POL', 'Политика'), ('SOC', 'Общество'), ('TEC', 'Наука и технологии'), ('ECN', 'Экономика'), ('REL', 'Религия'), ('WIL', 'Живая природа'), ('ECO', 'Экология')], default='NEW', max_length=3, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Пост комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating_comment',
            field=models.IntegerField(default=0, verbose_name='Рейтинг комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(blank=True, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_in_comment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_post',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='Категория поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0, verbose_name='Рейтинг поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(blank=True, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.CharField(max_length=255, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type_post',
            field=models.CharField(choices=[('NE', 'Новость'), ('AR', 'Статья')], max_length=2, verbose_name='Вид поста'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='subscriberscategory',
            name='subscribers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ник пользователя'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Наименование поста')),
            ],
        ),
    ]
