# Generated by Django 5.1.5 on 2025-04-18 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_postimage_options_postimage_link_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='link_images',
        ),
    ]
