# Generated by Django 5.1.5 on 2025-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_post_link_postlinkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='postlinkimage',
            name='link',
            field=models.TextField(blank=True, verbose_name='Ссылка на изображение'),
        ),
    ]
